# Generated by Django 4.0.6 on 2022-07-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeusers',
            old_name='challenge',
            new_name='participant',
        ),
    ]
