# Generated by Django 4.0.6 on 2022-07-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0002_rename_challenge_challengeusers_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(default='', max_length=15),
        ),
    ]
