# Generated by Django 4.0.6 on 2022-08-01 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0013_alter_user_python1_1'),
        ('challenge_app', '0005_rename_participant_challengeusers_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='num',
        ),
        migrations.AddField(
            model_name='challenge',
            name='tag',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='participant',
            field=models.ManyToManyField(related_name='challenges', through='challenge_app.ChallengeUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
