# Generated by Django 4.1 on 2022-08-04 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge_app', '0006_remove_challenge_num_challenge_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonChallenge1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='매일 파이썬 학습하기', max_length=200)),
                ('start', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('day1', models.BooleanField(default=False)),
                ('day2', models.BooleanField(default=False)),
                ('day3', models.BooleanField(default=False)),
                ('day4', models.BooleanField(default=False)),
                ('day5', models.BooleanField(default=False)),
                ('day6', models.BooleanField(default=False)),
                ('day7', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='challengeusers',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengeusers',
            name='user',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeUsers',
        ),
    ]
