# Generated by Django 4.0.6 on 2022-08-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0007_pythonchallenge1_remove_challengeusers_challenge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonchallenge1',
            old_name='start',
            new_name='start_date',
        ),
    ]
