# Generated by Django 4.0.6 on 2022-08-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0008_rename_start_pythonchallenge1_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonchallenge1',
            name='start_date',
        ),
    ]
