# Generated by Django 4.0.6 on 2022-08-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0009_remove_pythonchallenge1_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonchallenge1',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pythonchallenge1',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
