# Generated by Django 4.0.6 on 2022-08-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0010_pythonchallenge1_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pythonchallenge1',
            name='day7',
            field=models.IntegerField(default=0),
        ),
    ]
