# Generated by Django 4.0.6 on 2022-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python1_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='python2',
            field=models.BooleanField(default=True),
        ),
    ]
