# Generated by Django 4.0.6 on 2022-07-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python0',
            field=models.BooleanField(default=True),
        ),
    ]
