# Generated by Django 4.0.6 on 2022-07-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='python4',
            new_name='python1_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='python5',
            new_name='python1_2',
        ),
        migrations.AddField(
            model_name='user',
            name='python1_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='python1_4',
            field=models.BooleanField(default=False),
        ),
    ]
