# Generated by Django 4.0.6 on 2022-07-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_rename_python4_user_python1_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python0',
            field=models.BooleanField(default=True),
        ),
    ]
