# Generated by Django 4.0.6 on 2022-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attend',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attend',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attend',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attend',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attend',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attend',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
