# Generated by Django 4.0.6 on 2022-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_remove_user_python0_user_python4_alter_user_python1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python1_1',
            field=models.BooleanField(default=True),
        ),
    ]
