# Generated by Django 4.0.6 on 2022-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_user_python1_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='python1_1',
            field=models.BooleanField(default=False),
        ),
    ]
