# Generated by Django 4.0.6 on 2022-07-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_user_python1_3_alter_user_python2'),
        ('account_app', '0007_alter_user_python1_alter_user_python1_1'),
    ]

    operations = [
    ]
