# Generated by Django 4.0.6 on 2022-07-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_user_python0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='python1_1',
            field=models.BooleanField(default=True),
        ),
    ]
