# Generated by Django 4.0.6 on 2022-07-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_alter_user_python1_1'),
        ('account_app', '0011_alter_user_python1_alter_user_python1_1'),
    ]

    operations = [
    ]
