<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-28 15:35
=======
# Generated by Django 4.0.6 on 2022-07-28 16:15
>>>>>>> f097c9fda804d7c5b8755694fa4209cf8adc3fe8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('account_app', '0012_merge_20220727_1819'),
=======
        ('account_app', '0012_merge_20220727_1820'),
>>>>>>> f097c9fda804d7c5b8755694fa4209cf8adc3fe8
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python1_1',
            field=models.BooleanField(default=False),
        ),
    ]
