# Generated by Django 4.0.6 on 2022-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_merge_20220727_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='python1_1',
            field=models.BooleanField(default=False),
        ),
    ]
