# Generated by Django 4.0.6 on 2022-08-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_merge_20220727_2138'),
        ('account_app', '0014_pystepattend'),
    ]

    operations = [
    ]
