# Generated by Django 4.0.6 on 2022-08-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_merge_0012_merge_20220727_2138_0014_pystepattend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pystepattend',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
