# Generated by Django 4.0.6 on 2022-08-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_alter_pystepattend_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pystepattend',
            old_name='datetime',
            new_name='date',
        ),
    ]
