# Generated by Django 4.0.6 on 2022-08-09 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0018_remove_pystepattend_date_pystepattend_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pystepattend',
            name='datetime',
        ),
        migrations.AddField(
            model_name='pystepattend',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
