# Generated by Django 4.0.6 on 2022-08-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0019_remove_pystepattend_datetime_pystepattend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_join',
            field=models.BooleanField(default=False),
        ),
    ]
