# Generated by Django 4.0.6 on 2022-08-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0020_user_challenge_complete_user_challenge_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='python1_4',
            new_name='python2_1',
        ),
        migrations.AddField(
            model_name='user',
            name='python2_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='python2_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='python3_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='python3_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='python3_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='python5',
            field=models.BooleanField(default=False),
        ),
    ]
