# Generated by Django 4.0.6 on 2022-08-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0021_rename_python1_4_user_python2_1_user_python2_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_post',
            field=models.BooleanField(default=False),
        ),
    ]
